-- MySQL Script generated by MySQL Workbench
-- 09/02/24 23:24:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `roomId` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` VARCHAR(45) NULL,
  `roomType` VARCHAR(45) NULL,
  `bedType` VARCHAR(100) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roomId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(150) NOT NULL,
  `userType` VARCHAR(45) NOT NULL,
  `userPassword` VARCHAR(45) NOT NULL,
  `userTP` VARCHAR(45) NOT NULL,
  `userNIC` VARCHAR(45) NOT NULL,
  `userEmail` VARCHAR(200) NOT NULL,
  `userAddress` VARCHAR(150) NOT NULL,
  `userStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customersId` INT NOT NULL AUTO_INCREMENT,
  `cusFullName` VARCHAR(45) NOT NULL,
  `cusNIC` VARCHAR(45) NOT NULL,
  `cusTP` VARCHAR(45) NOT NULL,
  `cusEmail` VARCHAR(150) NOT NULL,
  `cusAddress` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`customersId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bookings` (
  `bookingId` INT NOT NULL AUTO_INCREMENT,
  `cusFullName` VARCHAR(150) NOT NULL,
  `cusNIC` VARCHAR(45) NOT NULL,
  `cusTP` VARCHAR(45) NOT NULL,
  `cusEmail` VARCHAR(150) NOT NULL,
  `cusAddress` VARCHAR(200) NOT NULL,
  `cusCheckIn` VARCHAR(45) NOT NULL,
  `cusCheckOut` VARCHAR(45) NOT NULL,
  `numberOfAduls` VARCHAR(45) NOT NULL,
  `roomType` VARCHAR(45) NULL,
  `roomNumber` VARCHAR(45) NULL,
  `payMethod` VARCHAR(45) NULL,
  `payStatus` VARCHAR(45) NULL,
  `customers_customersId` INT NOT NULL,
  PRIMARY KEY (`bookingId`, `customers_customersId`),
  INDEX `fk_bookings_customers_idx` (`customers_customersId` ASC),
  CONSTRAINT `fk_bookings_customers`
    FOREIGN KEY (`customers_customersId`)
    REFERENCES `mydb`.`customers` (`customersId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
